export const constants = {
    UPDATE_TODO: "UPDATE_TODO",
    SELECT_TODO: "SELECT_TODO",
    DESELECT_TODO: "DESELECT_TODO",
    START_FIREBASE_COMMUNICATION: "START_FIREBASE_COMMUNICATION",
    STOP_FIREBASE_COMMUNICATION: "STOP_FIREBASE_COMMUNICATION"
};

export default constants;